title: config
apps:
  api:
    port: integer
    privatePort: integer
    useCachingInterceptor: boolean
  eventsNotifier:
    port: integer
    privatePort: integer
libs:
  common:
    network:
      type: string
      enum: [devnet, testnet, mainnet]
    urls:
      api: string
      gateway: string
      queue: string
    mnemonics:
      first: string
    tokens:
      first: string
    database:
      host: string
      port: integer
      username:
        type: string
        required: false
      password:
        type: string
        required: false
      name: string
      tlsAllowInvalidCertificates:
        type: boolean
        default: false
    redis:
      host: string
      port: integer
    nativeAuth:
      maxExpirySeconds:
        type: integer
        default: 86400
      acceptedOrigins:
        type: array
        items: string
    security:
      admins:
        type: array
        items: string
        default: []
    rateLimiterSecret:
      type: string
      required: false
